// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';

/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVyHFsMpS7iVR0WLOQzI84SFoiOU52mRc',
    appId: '1:387766619607:web:1710492dfe9e94631b0f92',
    messagingSenderId: '387766619607',
    projectId: 'cmsc23-b2l-tayamora',
    authDomain: 'cmsc23-b2l-tayamora.firebaseapp.com',
    storageBucket: 'cmsc23-b2l-tayamora.appspot.com',
    measurementId: 'G-MKDDLMHQ40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT962whM36IcTHlS0GYEuy7aCZYIal91Q',
    appId: '1:387766619607:android:2f92580e0f67ca101b0f92',
    messagingSenderId: '387766619607',
    projectId: 'cmsc23-b2l-tayamora',
    storageBucket: 'cmsc23-b2l-tayamora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIFldw5uhTG30qsyuXcGcbTRxhGHbC-Lg',
    appId: '1:387766619607:ios:8d0e940d156f1a731b0f92',
    messagingSenderId: '387766619607',
    projectId: 'cmsc23-b2l-tayamora',
    storageBucket: 'cmsc23-b2l-tayamora.appspot.com',
    iosClientId: '387766619607-kqnift54d3fdlk2pht6pmqud9fve9g8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIFldw5uhTG30qsyuXcGcbTRxhGHbC-Lg',
    appId: '1:387766619607:ios:8d0e940d156f1a731b0f92',
    messagingSenderId: '387766619607',
    projectId: 'cmsc23-b2l-tayamora',
    storageBucket: 'cmsc23-b2l-tayamora.appspot.com',
    iosClientId: '387766619607-kqnift54d3fdlk2pht6pmqud9fve9g8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
